


const AnimalData = [
    {
        id: 1,
        url: '/corbettTiger.jpg',
        title: 'Indochinese Tiger',
        body: 'The Indochinese Tiger, a Bengal subspecies found in India and nearby areas, boasts a distinctive orange coat with black stripes. Despite symbolizing wild strength and beauty, it faces extinction threats.',
        intro: 'Imagine a big cat thats like a superstar in the jungles of places like Thailand, Vietnam, and other cool spots in Southeast Asia. Thats the Indochinese Tiger!',
        appear: 'These tigers are super special because they wear a beautiful coat thats like wearing a golden-orange or reddish-yellow jacket with cool black stripes all over their body, just like having fancy tiger tattoos!',
        HWM: 'They can measure around 8.5 to 9.5 feet (2.6 to 2.9 meters) in length, including their tail. In terms of weight, adult males can weigh between 330 to 430 pounds (150 to 195 kilograms).',
        HWF: 'They are generally slightly smaller than males. Females typically measure a bit shorter in length, and their weight can range from 220 to 300 pounds (100 to 136 kilograms).',
        lifeStyle: 'These tigers love to have their own space and are not big fans of hanging out with other tigers. They re like solo adventurers, exploring their jungle homes mostly at night.',
        food: 'They are not just big, they are really strong too! Their muscles help them run super-fast and catch their dinner, which could be deer, wild pigs, or other small animals.',
        fun1: 'Tigers are amazing athletes! They can jump impressive distances—up to 10 meters (33 feet) in a single leap!',
        fun2: 'Unlike many other cats, they actually enjoy taking a dip in the water to cool off or to chase prey. They are strong swimmers and can cross rivers or streams easily.',
        fun3: 'These tigers are very territorial. They mark their territory by scratching trees, spraying urine, and leaving scent markings to let other tigers know that the area is already taken.',
        warn: 'Unfortunately, these tigers are in serious trouble. They are critically endangered, which means they re at a very high risk of disappearing from the wild. The population of Indochinese Tigers has drastically decreased due to habitat loss, poaching, and illegal hunting.',
        preserve: 'This situation is sad and something we all need to work together to change. Protecting their homes and stopping poaching is super important to keep these amazing tigers around for future generations to enjoy.',
        pic1: '/corbettTiger2.jpg',
        pic2: '/corbettTiger3.jpg'
    },
    {
        id: 1,
        url: '/asianGoldenCat.jpg',
        title: 'Asian Golden Cat',
        body: 'The Asian golden cat, from Southeast Asia, sports a stunning golden coat. Despite its elusiveness, habitat loss and hunting pose significant threats to its conservation.',
        intro: 'Look over there! What is that beautiful wild cat thats like a hidden gem in the forests of Asia ? That my friend is the Asian Golden Cat!',
        appear: 'This feline friend has a stunning coat that can range from a rusty reddish-brown to a magnificent golden hue, just like the color of autumn leaves. But wait, that is not all! Some lucky ones might even have spots or stripes on their fur.',
        HWM: 'On average, males tend to be slightly larger than females. They can measure between 2.5 to 3.5 feet (75 to 105 centimeters) in length and weigh around 25 to 35 pounds (11 to 16 kilograms).',
        HWF: 'Females are generally smaller than males. They typically measure about 2 to 3 feet (60 to 90 centimeters) in length and weigh around 15 to 25 pounds (7 to 11 kilograms).',
        lifeStyle: 'They are strong and agile, with powerful legs that help them jump and climb through the trees. They have a special way of marking their territory too! They scratch trees and leave their scent so other cats know, "Hey, this is my home!"',
        food: 'Asian Golden Cats are like mysterious forest detectives, sneaking around during the night, exploring and hunting for their favorite snacks like birds, small mammals, or even fish!',
        fun1: 'One of the coolest things about these cats is their secret world of communication. They use different sounds like hisses, purrs, and even meows to talk to each other.',
        fun2: 'When they are not prowling around, they might just take a cool dip in a stream because these cats are pretty good swimmers too!',
        fun3: 'These cats are primarily active during the night, using their excellent night vision to hunt and explore their forest habitats under the cover of darkness.',
        warn: 'These amazing cats are super important for keeping the balance in their forest homes. They are like natures guardians, making sure everything stays just right.',
        preserve: 'Protecting their habitats is super important so that these majestic Asian Golden Cats can keep being the cool, wild adventurers they are!',
        pic1: '/goldenCat2.jpg',
        pic2: '/goldenCat3.jpg',
    },
    {
        id: 1,
        url: '/tapir.jpg',
        title: 'Tapir',
        body: 'The tapir, a distinctive mammal found in Central and South America, as well as Southeast Asia, is recognized for its charming appearance with a trunk-like snout.',
        intro: 'Hey, have you ever met an animal that is like a real-life combination of a pig, an elephant, and a horse ? Sound unbelievable, right? Well, that is the incredible Tapir!',
        appear: 'Picture this: they have these adorable snouts that look like short trunks, and their bodies are covered in a thick, tough skin that can be dark brown, gray, or black. When Tapir babies are born, they have cute stripes and spots that fade away as they grow up, making them even more adorable.',
        HWM: 'On average, male Tapirs can stand around 2 to 3 feet (60 to 90 centimeters) tall at the shoulder and measure about 6.6 to 8.2 feet (2 to 2.5 meters) in length from nose to tail. They can weigh anywhere from 550 to 880 pounds (250 to 400 kilograms).',
        HWF: 'Females are slightly smaller than males. On average, they stand about 2 to 2.6 feet (60 to 80 centimeters) tall at the shoulder and measure around 6 to 7.6 feet (1.8 to 2.3 meters) in length. Their weight ranges from 330 to 660 pounds (150 to 300 kilograms).',
        lifeStyle: 'Tapirs are absolute champs when it comes to swimming! They love to paddle around in rivers and lakes, using their snouts like snorkels to breathe while they explore the water. How cool is that?',
        food: 'These creatures are like gardeners of the forest—they munch on leaves, fruits, and plants, helping to spread seeds around as they wander.',
        fun1: 'They do not make a lot of noise and prefer to keep to themselves, except when they are communicating with each other through high-pitched whistles or squeaks.',
        fun2: 'Tapirs are fascinating because they are ancient animals! They have been around for a very long time and are considered living fossils, meaning they have existed in a similar form for millions of years.',
        fun3: 'Their snouts are quite flexible and versatile. Tapirs use them to grab leaves and fruits, much like a mini trunk. This special feature makes them exceptional foragers in their forest habitats.',
        warn: 'They are like natures little helpers, ensuring that the forest stays healthy and thriving.',
        preserve: 'Tapirs are essential for their ecosystems, and it is really important for us to protect their homes, ensuring they can continue being these fascinating, ancient creatures that bring so much uniqueness and charm to our world!',
        pic1: '/tapir2.jpg',
        pic2: '/tapir3.jpg',
    },
    {
        id: 1,
        url: '/blackBear.jpg',
        title: 'Asian Black Bear',
        body: 'The Asian black bear, also called the moon bear, showcases sleek black fur and a distinct V-shaped chest patch, making it a unique and easily recognizable species across Asia.',
        intro: 'Welcome to the world of Bears, a majestic creature that roams the forests like a silent guardian! Picture a bear that is both mysterious and powerful, and that is exactly what the Asian Black Bear embodies.',
        appear: 'What makes these black bears stand out is the unique patch on their chest, which might resemble a V-shaped marking or a crescent. It is like their very own emblem!',
        HWM: 'On average, males stand around 5 to 6 feet tall (1.5 to 1.8 meters) when standing on their hind legs and weigh approximately 300 to 440 pounds (136 to 200 kilograms).',
        HWF: 'Females are generally slightly smaller than males. On average, they stand about 4.5 to 5.5 feet tall (1.4 to 1.7 meters) when standing upright and weigh around 200 to 300 pounds (91 to 136 kilograms).',
        lifeStyle: 'Asian Black Bears are natural climbers, showcasing incredible agility as they navigate the trees using their strong claws. They even create cozy nests up in the branches for their restful moments.',
        food: 'In the culinary world of the forest, Asian Black Bears are gourmets! They savor a diverse diet, relishing fruits, berries, nuts, and insects alike. Their knack for finding food in unexpected places, like beehives, shows off their cleverness.',
        fun1: 'Just like their distant relative, the American black bear, Asian Black Bears have a fondness for honey. They will raid beehives in search of this sweet treat and are known to be quite resourceful in getting their share.',
        fun2: 'Asian Black Bears are known for their relaxed and slow-moving demeanor. They can be seen lounging in trees, showing a more chilled-out side compared to other bear species.',
        fun3: 'Despite their powerful presence, these bears are typically shy around humans',
        warn: 'Asian Black Bears have experienced habitat loss and fragmentation due to deforestation, which has greatly impacted their numbers. Additionally, illegal hunting and poaching for their body parts (used in traditional medicine) and bile farming (for the extraction of bear bile) have been major contributors to their decline.',
        preserve: 'These bears are essential for maintaining the balance in their ecosystems. Preserving their habitats is crucial to ensure that these remarkable bears continue to thrive as the magnificent guardians of the forests!',
        pic1: '/blackBear2.jpg',
        pic2: '/blackBear3.jpg',
    },
    {
        id: 5,
        url: '/spottedLinsang.jpg',
        title: 'Spotted Linsang',
        body: 'The Spotted Linsang, a small carnivorous mammal in Southeast Asia, stands out with its slender build and distinctive spotted fur, contributing to the region ecosystem.',
        intro: 'Step into the realm of the Spotted Linsang, a creature that is like a secret adventurer dwelling in the forests shadows. Picture a sleek predator, a blend of feline grace and the mysterious agility of a mongoose.',
        appear: 'Their coat is a work of art, a mesmerizing mix of reddish-brown fur adorned with dark spots or blotches, reminiscent of a tiny leopard. Each linsang boasts its own unique pattern, making them easily distinguishable.',
        HWM: 'Spotted Linsangs typically measure around 14 to 17 inches (35 to 43 centimeters) in body length, with an additional 13 to 17 inches (33 to 43 centimeters) for their tails. They weigh approximately 2 to 3 pounds (0.9 to 1.4 kilograms).',
        HWF: 'Both male and female Spotted Linsangs exhibit similar body sizes and appearances.',
        lifeStyle: 'They are natures nimble climbers, effortlessly scaling trees with their sharp claws, moving through the forest canopy with unmatched agility.',
        food: 'In the dining department, Spotted Linsangs have a carnivorous palate, indulging in small mammals, birds, reptiles, and insects. Their hunting skills are remarkable, relying on stealth to catch their prey.',
        fun1: 'While not particularly vocal, Spotted Linsangs communicate through soft chirps, clicks, and calls, likely used for social interactions and territorial signaling.',
        fun2: 'Spotted Linsangs are elusive creatures that prefer to keep a low profile. They are rarely spotted in the wild, adding to their air of mystery.',
        fun3: 'Each Spotted Linsang has its own distinct coat pattern of spots and blotches, much like a fingerprint. No two linsangs have the exact same markings.',
        warn: 'In the intricate tapestry of the forest, the Spotted Linsang plays a unique role, contributing to the delicate balance of their ecosystem. Their elusive nature and distinctive traits make them a captivating and essential part of the diverse wildlife landscape!',
        preserve: 'While they may be lesser-known, their unique features and behavior make them a fascinating and integral part of the wild world!',
        pic1: '/linsang2.jpg',
        pic2: '/linsang3.jpg',
    },
    {
        id: 6,
        url: '/Gaur.jpg',
        title: 'Gaur',
        body: 'Gaur, a magnificent wild ox found in Indochina. It showcases a robust build with a dark coat and distinctive white stockings on its legs, distinguishing it as a striking and iconic species in the region.',
        intro: 'Welcome to the world of the Gaur, a magnificent creature that is the largest wild cattle species on the planet! Imagine meeting a gentle giant, a symbol of strength and grace in the forest.',
        appear: 'Their coat varies from dark brown to almost black, providing excellent camouflage in their natural habitat. Adult Gaur showcase distinctive white stockings on their lower legs, and both males and females have curved horns that curve slightly backward.',
        HWM: 'They stand taller at the shoulder, usually measuring between 5.6 to 7.2 feet (1.7 to 2.2 meters). Bulls typically weigh an impressive 1,500 to 2,200 pounds (680 to 1,000 kilograms). They possess thicker necks and larger, more robust bodies compared to females.',
        HWF: 'Cows are slightly smaller than bulls. On average, they stand around 4.9 to 5.6 feet (1.5 to 1.7 meters) at the shoulder and weigh approximately 880 to 1,320 pounds (400 to 600 kilograms).',
        lifeStyle: 'Gaur usually live in small herds led by a dominant bull. They communicate using low grunts, bellows, and snorts, establishing social bonds and maintaining herd cohesion.',
        food: 'These peaceful giants are primarily herbivores, feeding on grasses, leaves, shoots, and fruits. Despite their immense size, Gaur are surprisingly agile and can reach impressive speeds when needed.',
        fun1: 'Despite their massive size, Gaur are known for their gentle nature. They are generally shy and tend to avoid confrontations, preferring to graze peacefully in their natural habitats.',
        fun2: 'Despite their bulky appearance, Gaur are surprisingly agile. They are capable of leaping over barriers and fences when they need to, showcasing their athleticism despite their size.',
        fun3: 'Gaur are highly adaptable creatures and can thrive in a variety of habitats, including tropical and subtropical forests, grasslands, and hilly terrains.',
        warn: 'The Gaur holds a significant place in the forest ecosystems, embodying the spirit of the wild and representing the beauty of these natural landscapes.',
        preserve: 'Unfortunately, these magnificent animals face threats from habitat loss and poaching. Conservation efforts are crucial to protect their habitats and ensure the survival of these gentle giants in the wild.',
        pic1: '/gaur2.jpg',
        pic2: '/gaur3.jpg',
    },
    {
        id: 7,
        url: '/leopard.jpg',
        title: 'Indochinese leopard',
        body: 'The Indochinese leopard is a Southeast Asian subspecies of leopard,known for its stunning golden-yellow coat with dark spots and rosettes, adapted to the diverse habitats within its range.',
        intro: 'Step into the enigmatic domain of the Indochinese Leopard, a majestic and elusive big cat that prowls the forests with a sense of regal mystery.',
        appear: 'Picture a creature adorned in a coat of golden-hued fur, marked with exquisite rosettes, embodying both strength and stealth. Their coat, ranging from tawny to golden-yellow, features distinct rosettes and spots that serve as effective camouflage in their forested environments.',
        HWM: 'They typically stand around 2 to 2.5 feet (60 to 75 centimeters) tall at the shoulder and can measure approximately 4.5 to 6.25 feet (1.4 to 1.9 meters) in body length. Males typically weigh between 70 to 130 pounds (32 to 59 kilograms).',
        HWF: 'Females are slightly smaller than males. On average, they stand around 1.8 to 2.2 feet (55 to 67 centimeters) tall at the shoulder and measure about 3.8 to 5.5 feet (1.15 to 1.7 meters) in body length. Females generally weigh between 50 to 90 pounds (23 to 41 kilograms).',
        lifeStyle: 'The Indochinese Leopard is a magnificent predator, characterized by its sleek physique and remarkable adaptability to various landscapes, including dense forests and mountainous terrains',
        food: 'Indochinese Leopards are skilled climbers and proficient hunters, preying upon a variety of animals like deer, wild boar, and smaller mammals. Their hunting prowess and elusive nature make them apex predators in their ecosystems.',
        fun1: 'Like many big cats, Indochinese Leopards mark their territories by leaving scent marks on trees, rocks, and other objects within their range.',
        fun2: 'Indochinese Leopards are known for their elusive nature, making them challenging to study. Their secretive behavior and stealthy movements contribute to their air of mystery.',
        fun3: 'Indochinese Leopards are incredible climbers and swimmers. ',
        warn: 'Unfortunately, the Indochinese Leopard faces significant threats from habitat loss, poaching, and human-wildlife conflicts, leading to a decline in their populations. Conservation efforts are crucial to ensure the survival of this endangered species.',
        preserve: 'Preserving their habitats and establishing conservation initiatives are essential steps in safeguarding the future of the Indochinese Leopard. These majestic felines symbolize the untamed beauty of nature and underscore the importance of protecting our diverse wildlife.',
        pic1: '/leopard2.jpg',
        pic2: '/leopard3.jpg',
    },
    {
        id: 8,
        url: '/javanRhino.jpg',
        title: 'Javan rhinoceros',
        body: 'The Javan rhinoceros, critically endangered and rare. Its small size and single horn distinguish it, facing grave threats from habitat loss and poaching, urging immediate conservation actions.',
        intro: 'Enter the world of the Javan Rhinoceros, a majestic and critically endangered giant residing in the dense forests with an aura of ancient grandeur. Envision a magnificent creature adorned with thick, rugged skin, representing resilience and exceptional rarity.',
        appear: 'The Javan Rhinoceros is one of the rarest and most enigmatic creatures on Earth, distinguished by its single horn and heavy-set body. This magnificent rhino is dark gray to black in color and sports a hide adorned with deep folds, adding to its unique appearance.',
        HWM: 'They typically stand around 5.8 to 6.6 feet (1.8 to 2 meters) tall at the shoulder. The body length of a Javan Rhinoceros, from the tip of the snout to the base of the tail, is approximately 9.8 to 12.1 feet (3 to 3.7 meters). And their weight can range between 1,984 to 5,071 pounds (900 to 2,300 kilograms).',
        HWF: 'Javan Rhinoceroses do not display significant size differences between males and females.',
        lifeStyle: 'These rhinos once roamed across Southeast Asia, inhabiting dense tropical rainforests and swampy habitats.',
        food: 'Javan Rhinoceroses are mainly herbivores, feeding on leaves, twigs, and shoots found in their forested habitats. Their large size and solitary nature make them elusive and challenging to study.',
        fun1: 'Unlike some other rhino species, Javan Rhinoceroses typically have a single horn. Their horn is relatively small compared to other rhino species, usually measuring less than 10 inches (25 centimeters).',
        fun2: 'Like other rhino species, Javan Rhinoceroses enjoy wallowing in mud. They do this to regulate their body temperature and protect their skin from parasites and insects.',
        fun3: 'These rhinos are skilled swimmers and are often found in areas near rivers and swamps, where they can wallow and cool off.',
        warn: 'Sadly, habitat loss, poaching, and their critically low numbers have pushed these majestic creatures to the brink of extinction. Conservation efforts are urgently needed to protect their remaining habitats and safeguard their future.',
        preserve: 'Preserving their habitats and establishing effective conservation programs are vital steps to ensure the survival of the Javan Rhinoceros. These magnificent beings symbolize the irreplaceable biodiversity of our planet and underscore the importance of protecting and cherishing our endangered species.',
        pic1: '/rhino2.jpg',
        pic2: '/rhino3.jpg',
    },
    {
        id: 9,
        url: '/pangolin.jpg',
        title: 'Chinese Pangolin',
        body: 'The Chinese pangolin, known for its protective scales covering its body. It features a slender frame and a specialized long tongue, adapted for feeding on ants and termites.',
        intro: 'Welcome to the enchanting world of the Chinese Pangolin, a marvelous creature that ambles through forests with an air of gentle grace. Imagine a small, armored mammal covered in scales, embodying both resilience and charm.',
        appear: 'This pangolin species has a distinct appearance with its small, cone-shaped head, a long, slender body, and a prehensile tail that aids in climbing trees and handling objects.',
        HWM: 'They typically measure around 50 to 60 centimeters (20 to 24 inches) from head to the base of the tail. Chinese Pangolins usually weigh between 2 to 7 kilograms (4.4 to 15.4 pounds).',
        HWF: 'Male and female Chinese Pangolins are generally similar in size, with little sexual dimorphism (physical differences between sexes).',
        lifeStyle: 'The Chinese Pangolin is a unique and elusive species, characterized by its tough, overlapping scales covering its body, providing a natural armor against predators. These scales, made of keratin, are similar in structure to human fingernails.',
        food: 'Chinese Pangolins are primarily nocturnal and solitary creatures, spending their nights foraging for ants, termites, and insects using their long, sticky tongues. Their diet consists mainly of ants and termites found in forested habitats.',
        fun1: 'Despite their terrestrial habits, Chinese Pangolins are capable climbers and use their prehensile tails to aid in climbing trees.',
        fun2: 'Their tongues can extend up to 40 centimeters (16 inches) and are coated with sticky saliva, perfect for catching ants and termites within crevices.',
        fun3: 'The Chinese Pangolins body is covered in tough, overlapping scales made of keratin, acting as armor to protect against predators.',
        warn: 'Unfortunately, Chinese Pangolins face severe threats due to illegal wildlife trade, habitat loss, and hunting for their scales, which are believed to have medicinal properties in traditional Chinese medicine.',
        preserve: 'The Chinese Pangolin remains a symbol of natural wonder, resilience, and the need for conservation, reminding us of the importance of protecting and preserving our precious wildlife.',
        pic1: '/pangolin2.jpg',
        pic2: '/pangolin3.jpg',
    },
    {
        id: 10,
        url: '/elephant4.jpg',
        title: 'Asian Elephant',
        body: 'The Asian elephant, famed for its large ears, long trunk, and tusks, inhabits diverse habitats in Asia and plays a vital role in its ecosystem. Conservation efforts aim to protect this remarkable species.',
        intro: 'Explore the domain of the Asian Elephant, a revered and awe-inspiring creature moving through diverse landscapes with a grace that reflects its wisdom. Picture this magnificent being, defined by its broad ears, elongated trunk, and an undeniable aura of majesty.',
        appear: 'The Asian Elephant is the largest land animal in Asia, standing tall with a remarkable physique. They are known for their thick gray skin, wrinkled appearance, and distinctive trunk that serves multiple purposes, acting as a nose, hand, and tool.',
        HWM: 'They can stand up to around 8.2 to 9.8 feet (2.5 to 3 meters) at the shoulder and weigh between 8,800 to 12,000 pounds (4,000 to 5,400 kilograms).',
        HWF: 'Females are slightly smaller, usually standing around 7.5 to 8.9 feet (2.3 to 2.7 meters) at the shoulder and weighing between 5,500 to 6,600 pounds (2,500 to 3,000 kilograms).',
        lifeStyle: 'These magnificent creatures are highly intelligent and social, forming strong family bonds within their herds. They communicate through a variety of sounds, body language, and touch, displaying a complex social structure.',
        food: 'Asian Elephants are herbivores, primarily feeding on grasses, leaves, bark, and fruits found in their habitats. Their vast territories range from dense forests to grasslands, where they play a crucial role in shaping their ecosystems.',
        fun1: 'Their trunk, which consists of around 40,000 muscles, enables them to perform intricate tasks, such as grasping objects, pulling down branches, and even spraying water for bathing and cooling down.',
        fun2: 'Asian Elephants are highly social animals, living in matriarchal herds led by the oldest female, who guides and protects the group.',
        fun3: 'hey possess impressive cognitive abilities and have a remarkable memory, able to recall distant locations, recognize other individuals, and remember previous experiences.',
        warn: 'Unfortunately, Asian Elephants face threats from habitat loss, human-wildlife conflict, and illegal poaching. Conservation efforts are vital to protect these majestic animals and preserve their habitats.',
        preserve: 'The Asian Elephant stands as a testament to the beauty and importance of biodiversity, reminding us of the need to protect and cherish these magnificent creatures and their habitats.',
        pic1: '/AElephant2.jpg',
        pic2: '/AElephant3.jpg',
    },
    {
        id: 11,
        url: '/crestedArgus.jpg',
        title: 'Crested Argus',
        body: 'The Crested Argus, is notable for its stunning appearance, featuring intricate plumage and a distinctive crest. Known for its unique calls and elaborate courtship displays.',
        intro: 'Crested Argus, a stunning bird that roams the forest floor with an air of elegance and splendor. A magnificent creature adorned with intricate patterns, bold colors, and an impressive crest, symbolizing its beauty and grace.',
        appear: 'The Crested Argus is a large, ground-dwelling bird native to the forests of Southeast Asia. Its striking appearance features intricate plumage, with bold, eye-catching patterns of dark feathers adorned with intricate white and buff-colored markings.',
        HWM: 'They typically measure about 70-80 centimeters (28-31 inches) in length and weigh around 2.5-3.5 kilograms (5.5-7.7 pounds).',
        HWF: 'Females are slightly smaller, usually measuring about 65-75 centimeters (26-30 inches) in length and weighing approximately 2-3 kilograms (4.4-6.6 pounds).',
        lifeStyle: 'Crested Argus are known for their unique and enchanting courtship displays, where males perform intricate dances and vocalizations to attract females during the breeding season.',
        food: 'These birds have an elusive nature, preferring the dense undergrowth of the forests, where they forage for food. Their diet mainly consists of insects, invertebrates, seeds, and fruits found within their habitat.',
        fun1: 'One of the most distinctive features of the Crested Argus is its striking crest atop its head, resembling a crown. This crest, composed of elongated feathers, adds to its regal appearance and makes it easily recognizable among the forest foliage.',
        fun2: 'Crested Argus are shy and elusive birds, often remaining hidden in dense forest undergrowth. Their cryptic plumage and secretive nature make them challenging to spot in their natural habitat.',
        fun3: 'During the breeding season, male Crested Argus perform elaborate courtship displays involving intricate dances and vocalizations to attract females, showcasing their captivating behavior.',
        warn: 'Unfortunately, these magnificent birds face threats due to habitat loss and hunting pressures. Conservation efforts are crucial to protect their forest habitats and ensure the survival of the Crested Argus in the wild.',
        preserve: 'Preserving the forests where these birds thrive is essential to safeguard the unique beauty and cultural significance of the Crested Argus, a true jewel of the Southeast Asian forests.',
        pic1: '/argus2.jpg',
        pic2: '/argus3.jpg',
    },
    {
        id: 12,
        url: '/baerPochard.jpg',
        title: 'Baer Pochard',
        body: 'Baer Pochard, a diving duck species found in parts of East Asia, features a striking appearance with a chestnut-colored head, contrasting black neck, and a distinctive pale eye.',
        intro: 'Baer Pochard, an extraordinary diving duck that inhabits wetlands with grace and beauty. Imagine a striking bird adorned with distinctive plumage, representing both elegance and uniqueness.',
        appear: 'The Baer Pochard is a medium-sized diving duck known for its captivating appearance. The male sports a glossy black head, chestnut-brown body, and striking white eyes, while the female exhibits a more subdued coloration with brown plumage and a lighter face.',
        HWM: 'They typically measure about 42-46 centimeters (16.5-18 inches) in length and weigh around 700-900 grams (1.5-2 pounds).',
        HWF: 'Females are slightly smaller, usually measuring about 40-44 centimeters (15.7-17.3 inches) in length and weighing approximately 600-800 grams (1.3-1.8 pounds).',
        lifeStyle: 'Baer Pochards are migratory birds, traveling long distances during the winter months to warmer regions in East Asia, including China and Southeast Asia, where they form large flocks',
        food: 'These pochards are skilled divers, navigating through water bodies with ease to forage for their food. Their diet primarily consists of aquatic plants, seeds, and invertebrates found in freshwater lakes, marshes, and ponds.',
        fun1: 'Baer Pochards communicate using a variety of calls, including soft whistles and quacking sounds.',
        fun2: 'They are social birds, often seen in flocks during migration or in small groups in their breeding grounds.',
        fun3: 'They are migratory and undertake long-distance journeys during winter, traveling to warmer regions in East Asia, including China and Southeast Asia.',
        warn: 'Unfortunately, the Baer is Pochard faces significant threats, primarily due to habitat loss, degradation of wetlands, and hunting pressures. These factors have led to a decline in their populations, categorizing them as critically endangered.',
        preserve: 'Preserving wetlands and creating protected areas are crucial steps in ensuring the survival of the Baer Pochard, a bird of immense beauty and importance in maintaining the ecological balance of freshwater habitats.',
        pic1: '/pochard2.jpg',
        pic2: '/pochard3.jpg',
    },
    {
        id: 13,
        url: '/asianOpenbill.jpg',
        title: 'Asian Openbill',
        body: 'The Asian Openbill, a stork found in South and Southeast Asia, stands out for its bill with a noticeable gap. Thriving in wetland habitats, it feeds on mollusks and snails using its uniquely structured bill.',
        intro: 'A bird adorned with a peculiar bill that resembles a gap, which distinguishes it from other storks. An extraordinary bird that graces wetlands and rice fields with its unique appearance and behavior, that is the Asian Openbill',
        appear: 'The Asian Openbill is a medium-sized stork known for its distinctive bill, which has a distinctive gap or notch near the tip. This gap gives the appearance of a bill that does not fully close, creating a specialized tool for extracting snails and mollusks from their shells, its primary diet.',
        HWM: 'They typically measure about 68 to 86 centimeters (27 to 34 inches) in length. Asian Openbills usually weigh around 1.3 to 1.5 kilograms (2.9 to 3.3 pounds).',
        HWF: 'In Asian Openbills, sexual dimorphism in size between males and females is not significant. Both sexes have very similar sizes.',
        lifeStyle: 'These storks are known to gather in large flocks during the breeding season, building nests in trees near water bodies. They exhibit a remarkable communal nesting behavior, often nesting in colonies.',
        food: 'These storks are often found in marshes, swamps, and flooded fields, where they forage for aquatic creatures like snails, mollusks, and occasionally small frogs and insects. They use their unique bill to pry open shells and extract prey.',
        fun1: 'Asian Openbills are relatively silent birds, with occasional bill clattering sounds during interactions or while handling prey.',
        fun2: 'In terms of appearance, the Asian Openbill typically has a black and white plumage, with a contrasting beak that stands out. Their coloring aids in camouflage amidst the aquatic habitats they frequent.',
        fun3: 'They exhibit a remarkable communal nesting behavior, often nesting in colonies.',
        warn: '',
        preserve: 'Overall, the Asian Openbill stands as a unique and remarkable species, exemplifying specialized adaptations for feeding and demonstrating interesting communal behaviors during the breeding season.',
        pic1: '/openbill2.jpg',
        pic2: '/openbill3.jpg',
    },
    {
        id: 14,
        url: '/silverPheasant.jpg',
        title: 'Silver Pheasant',
        body: 'The Silver Pheasant in East Asia boasts stunning silver-white plumage, vivid red facial skin, and an impressive tail, showcasing elegance in dense forests during courtship displays.',
        intro: 'Step into the captivating world of the Silver Pheasant, a majestic avian resident of forested domains. Envision an exquisite bird adorned with resplendent plumage, embodying grace and captivating beauty amidst the woodland landscapes.',
        appear: 'The Silver Pheasant is a large and visually stunning bird, known for its striking appearance. The male Silver Pheasant boasts a remarkable plumage with intricate patterns of metallic silver-gray feathers accented by black markings and a distinct red facial patch, while the female exhibits more subdued brown plumage with black barring.',
        HWM: 'They typically measure about 100 to 120 centimeters (39 to 47 inches) in length, including their ornate tail feathers, and weigh approximately 1 to 1.5 kilograms (2.2 to 3.3 pounds).',
        HWF: 'Females are slightly smaller, usually measuring around 50 to 60 centimeters (20 to 24 inches) in length and weighing approximately 0.9 to 1.2 kilograms (2 to 2.6 pounds).',
        lifeStyle: 'The males of this species are particularly known for their impressive courtship displays during the breeding season. They perform elaborate dances, spreading their striking tail feathers and calling loudly to attract females.',
        food: 'These pheasants inhabit dense forests and wooded areas, where they forage for a varied diet consisting of seeds, berries, insects, and small invertebrates found in their woodland habitats.',
        fun1: 'Silver Pheasants are relatively shy and prefer to remain hidden in the undergrowth, making them challenging to spot in their natural habitat.',
        fun2: 'Their cryptic plumage provides excellent camouflage among the forest foliage.',
        fun3: 'These birds are typically seen in small groups or pairs and are relatively quiet, with occasional calls and soft clucking sounds.',
        warn: 'The Silver Pheasant represents a symbol of natural beauty and elegance within forested landscapes, showcasing remarkable plumage and behaviors during courtship that make it an awe-inspiring species to behold.',
        preserve: '',
        pic1: '/SPheasants2.jpg',
        pic2: '/SPheasants3.jpg',
    },
    {
        id: 15,
        url: '/whiteCrownedHornbill.jpg',
        title: 'White Crowned Hornbill',
        body: 'The White-crowned Hornbill, found in Southeast Asia forests, features a distinctive white head and black body. This bird plays a vital role in seed dispersal due to its unique bill.',
        intro: 'White-crowned Hornbill, a remarkable bird that graces the forests with its unique appearance and aerial prowess.',
        appear: 'The White-crowned Hornbill is a medium-sized bird known for its distinctive appearance. The most striking feature is its white-colored head crowned with black markings, accentuating its majestic presence. Additionally, the male of the species sports a remarkable casque atop its bill, resembling a horn-like structure, adding to its intriguing appearance.',
        HWM: 'They typically measure about 75 to 85 centimeters (30 to 33 inches) in length and weigh approximately 1.5 to 2 kilograms (3.3 to 4.4 pounds).',
        HWF: 'Females are slightly smaller, usually measuring around 70 to 80 centimeters (28 to 31 inches) in length and weighing approximately 1.2 to 1.8 kilograms (2.6 to 4 pounds).',
        lifeStyle: 'One of the most remarkable behaviors of these birds is their breeding habits. They often nest in tree cavities, where the female seals herself inside the nest using a mixture of mud, fruit pulp, and droppings. During this period, the male provides food to the female and the chicks through a small opening.',
        food: 'White-crowned Hornbills are fruit-eating birds, feasting on a variety of fruits, figs, insects, and small reptiles found in their forest habitats. Their unique bill structure allows them to pluck fruits and catch insects with precision.',
        fun1: 'These hornbills are primarily found in tropical forests, where they exhibit an arboreal lifestyle, flying gracefully from tree to tree. They possess strong bills and dexterous feet adapted for grasping and maneuvering among the branches.',
        fun2: 'White-crowned Hornbills are agile and skilled flyers, navigating the forest canopy with ease.',
        fun3: 'The male White-crowned Hornbill sports a horn-like casque atop its bill, which is used for amplifying calls and as a display during courtship rituals. The casque is absent in females, who have a smaller bill.',
        warn: 'These hornbills are not only visually striking but also play a crucial role in seed dispersal within their habitats, contributing significantly to forest regeneration.',
        preserve: 'The White-crowned Hornbill stands as a symbol of natural beauty and ecological importance within the forested landscapes, showcasing unique physical attributes and intriguing behaviors that make it an enchanting species to behold.',
        pic1: '/hornbill2.jpg',
        pic2: '/hornbill3.png',
    },
    {
        id: 16,
        url: '/siameseCrocodile.jpg',
        title: 'Siamese Crocodile',
        body: 'The Siamese crocodile, native to Southeast Asia, is critically endangered and features a distinctive broad snout and bony plates on its back.',
        intro: 'Siamese Crocodile, a fascinating and critically endangered reptile that navigates the waters with stealth and ancient grace. Picture a remarkable crocodilian species adorned with distinctive features, showcasing its importance in the ecosystem.',
        appear: 'The Siamese Crocodile, a medium-sized crocodilian, is characterized by its relatively slender body and a broad snout. It is typically dark olive-brown in color with visible bony plates, or scutes, along its back, adding to its unique appearance.',
        HWM: 'They usually measure about 2.5 to 3 meters (8.2 to 9.8 feet) in length and weigh around 150 to 250 kilograms (330 to 550 pounds).',
        HWF: 'Females are slightly smaller, typically measuring around 2 to 2.5 meters (6.6 to 8.2 feet) in length and weighing approximately 100 to 150 kilograms (220 to 330 pounds).',
        lifeStyle: 'These crocodiles are native to freshwater habitats such as rivers, marshes, and lakes in Southeast Asia. They are well-adapted swimmers, using their powerful tails to propel themselves through the water with agility.',
        food: 'Siamese Crocodiles have a diverse diet, feeding on fish, amphibians, small mammals, and sometimes birds. They are ambush predators, patiently waiting near the water edge for prey to approach before striking with impressive speed.',
        fun1: 'Siamese Crocodiles are considered living fossils, having existed for millions of years and representing an ancient lineage of crocodilians.',
        fun2: 'Female Siamese Crocodiles are attentive mothers, guarding their nests and young hatchlings, protecting them from predators and helping them reach the water.',
        fun3: 'Their body is covered in distinctive scales, or scutes, which are more prominent compared to other crocodile species, providing protection and thermal regulation.',
        warn: 'One of the most distinguishing characteristics of the Siamese Crocodile is its critically endangered status. These crocodiles have faced severe population declines due to habitat loss, illegal hunting, and human-wildlife conflicts.',
        preserve: 'Conservation efforts are crucial for the survival of the Siamese Crocodile, including habitat protection, breeding programs, and community education to reduce human impact on their habitats.',
        pic1: '/crocodile2.jpg',
        pic2: '/crocodile3.jpg',
    },
    {
        id: 17,
        url: '/asianWaterMonitor.jpg',
        title: 'Asian Water Moniter',
        body: 'The Asian water monitor, a large reptile in South and Southeast Asia, is recognized for its size, powerful tail, and unique patterned skin. Found near water, it serves as an important predator in its ecosystem.',
        intro: 'Welcome to the fascinating realm of the Asian Water Monitor, a remarkable and versatile lizard that thrives in diverse habitats with its sleek and powerful presence.',
        appear: 'These monitors have a distinct appearance, featuring a long, muscular body covered in rugged scales that provide protection and aid in temperature regulation. Their strong, clawed feet enable them to climb, swim, and dig efficiently.',
        HWM: 'They usually measure about 1.5 to 2 meters (5 to 6.5 feet) in length and can weigh around 20 to 30 kilograms (44 to 66 pounds) on average.',
        HWF: 'Females are generally smaller, typically measuring about 1 to 1.5 meters (3 to 5 feet) in length and weighing approximately 10 to 20 kilograms (22 to 44 pounds) on average.',
        lifeStyle: 'Asian Water Monitors possess acute senses, including a keen sense of smell facilitated by their forked tongues, which they use to detect prey and navigate their surroundings.',
        food: 'As proficient swimmers and expert climbers, Asian Water Monitors are apex predators, preying on a varied diet that includes fish, amphibians, small mammals, birds, eggs, and carrion.',
        fun1: 'The Asian Water Monitor is one of the largest lizard species globally, known for its impressive size and adaptability to various ecosystems, including forests, swamps, riversides, and even urban areas.',
        fun2: 'These lizards also play a vital ecological role by controlling populations of pests like rodents and scavenging on carrion, contributing to the ecosystems balance.',
        fun3: 'The Asian Water Monitor stands as an emblem of adaptability and ecological importance, underscoring the significance of preserving their habitats and fostering harmonious coexistence between humans and wildlife.',
        warn: 'Despite their adaptability and resilience, Asian Water Monitors face threats due to habitat destruction, human-wildlife conflict, and illegal trade for their skins and meat.',
        preserve: 'Conservation efforts aim to mitigate these threats by preserving their habitats, raising awareness, and implementing measures to protect these impressive reptiles.',
        pic1: '/monitor2.jpg',
        pic2: '/monitor3.jpg',
    },
    {
        id: 18,
        url: '/chineseWaterDragon.jpg',
        title: 'Chinese Water Dragon',
        body: 'The Chinese water dragon is a vibrant, adaptable lizard from China and Southeast Asia, popular as a pet due to its striking appearance and gentle nature.',
        intro: 'Chinese Water Dragon, a captivating reptile known for its grace and distinctive appearance with a long, slender body, vibrant coloring, and a notable affinity for water, embodying both elegance and adaptability.',
        appear: 'These remarkable lizards display striking physical features, including a long tail, a slender yet robust body, and a crest of spikes running down their back to the base of their tails.',
        HWM: ' They usually measure about 80 to 100 centimeters (31 to 39 inches) in total length, including their tails, and can weigh around 300 to 500 grams (0.7 to 1.1 pounds) on average.',
        HWF: 'Females are generally a bit smaller, typically measuring about 60 to 80 centimeters (24 to 31 inches) in length and weighing approximately 200 to 300 grams (0.4 to 0.7 pounds) on average.',
        lifeStyle: 'Chinese Water Dragons are arboreal and semi-aquatic, demonstrating impressive climbing abilities and a penchant for spending time near water sources, such as rivers, streams, and ponds.',
        food: 'Their diet primarily consists of insects, small vertebrates, fruits, and vegetation, which they hunt for in both terrestrial and aquatic environments.',
        fun1: 'One of their most distinctive traits is their stunning coloration, featuring shades of green, blue, and sometimes yellow, complemented by intricate patterns and markings, which help camouflage them amidst their lush, forested habitats.',
        fun2: 'They communicate through body language, visual displays, and sometimes vocalizations, including hissing or soft chirping sounds.',
        fun3: 'Chinese Water Dragons bask in the sun to regulate their body temperature, often seen lounging on rocks or branches.',
        warn: 'These lizards are known for their docile nature, making them popular in the exotic pet trade. However, their captive trade poses a threat to their wild populations due to habitat loss and collection for the pet industry.',
        preserve: 'As mesmerizing inhabitants of Asian ecosystems, preserving the natural habitats of Chinese Water Dragons is crucial to ensuring the conservation of this species and maintaining the delicate balance of their ecosystems.',
        pic1: '/waterDragon2.jpg',
        pic2: '/waterDragon3.jpg',
    },
    {
        id: 19,
        url: '/tokayGecko.jpg',
        title: 'Tokay Gecko',
        body: 'The Tokay gecko, known for its vibrant blue-gray body and orange spots, is found in Southeast Asia. Popular in the exotic pet trade for its striking appearance and distinctive calls.',
        intro: 'Step into the mesmerizing world of the Tokay Gecko, an iconic lizard renowned for its striking appearance and haunting vocalizations. Envision a creature adorned with vivid blue-gray skin adorned with vibrant orange or red spots, and known for its distinctive calls echoing through the night.',
        appear: 'Hailing from various parts of Asia, including Southeast Asia and the Indian subcontinent, the Tokay Gecko boasts a robust physique adorned with an eye-catching color scheme—a stunning display of natures artistry',
        HWM: 'They usually measure about 25 to 30 centimeters (10 to 12 inches) in total length, including their tails, and can weigh around 150 to 200 grams (5 to 7 ounces) on average.',
        HWF: 'Females are generally a bit smaller, typically measuring about 20 to 25 centimeters (8 to 10 inches) in length and weighing approximately 100 to 150 grams (3 to 5 ounces) on average.',
        lifeStyle: 'Thriving in forested environments and adapting seamlessly to urban landscapes, these nocturnal creatures are skilled climbers, scaling various surfaces with specialized toe pads, ensuring their adeptness on walls and ceilings.',
        food: 'As carnivorous predators, Tokay Geckos feast on an assortment of insects, small creatures, and sometimes even fellow geckos, using their acute vision and stealthy hunting techniques.',
        fun1: 'Tokay Geckos are known for their loud and repetitive "to-kay, to-kay" or "gek-ko, gek-ko" calls, which are often heard during the night.',
        fun2: 'These geckos possess the remarkable ability to detach their tails when threatened and later regenerate them, though the regenerated tails may have a different appearance.',
        fun3: 'Tokay Geckos are adept climbers, utilizing specialized toe pads covered in microscopic hairs that enable them to scale various surfaces, including vertical walls and ceilings.',
        warn: '',
        preserve: 'Despite their allure, Tokay Geckos face threats from illegal wildlife trade, impacting their populations and habitats. Conservation efforts and public awareness play pivotal roles in safeguarding these captivating reptiles for future generations to marvel at.',
        pic1: '/gecko2.jpg',
        pic2: '/gecko3.jpg',
    },
    {
        id: 20,
        url: '/elongatedTortoise.jpg',
        title: 'Elongated tortoise',
        body: 'The Elongated tortoise from Southeast Asia is known for its long, narrow shell and distinctive patterns. Cherished in the pet trade for its unique appearance and calm nature.',
        intro: 'Imagine a creature adorned with a sleek, elongated shell and a calm disposition, embodying both grace and resilience in its existence. That is the Elongated Tortoise, a captivating reptile known for its distinctive appearance and gentle nature.',
        appear: 'One of the most remarkable physical features of the Elongated Tortoise is its elongated, slightly domed carapace, which provides protection and flexibility for the tortoise movements.',
        HWM: 'They typically measure about 20 to 25 centimeters (8 to 10 inches) in carapace length and can weigh approximately 1 to 1.5 kilograms (2.2 to 3.3 pounds) on average.',
        HWF: 'Females are usually a bit smaller, measuring around 15 to 20 centimeters (6 to 8 inches) in carapace length and weighing about 0.5 to 1 kilogram (1.1 to 2.2 pounds) on average.',
        lifeStyle: 'The Elongated Tortoise, scientifically named Indotestudo elongata, is a species native to various regions in Southeast Asia, including parts of Myanmar, Thailand, Vietnam, Laos, and Cambodia. These tortoises display an impressive range of colors and patterns on their shells, ranging from shades of brown and yellow to intricate patterns of radiating lines and spots, adding to their aesthetic appeal.',
        food: 'Elongated Tortoises are predominantly terrestrial, inhabiting diverse habitats such as grasslands, scrublands, and forest edges. They spend their time foraging for vegetation, including leaves, flowers, and fruits, as well as occasionally consuming small invertebrates.',
        fun1: 'Known for their docile and calm temperament, Elongated Tortoises are often sought after as pets.',
        fun2: 'While they are generally active during the day, they might exhibit nocturnal activity during hot weather or in captivity.',
        fun3: 'Females lay clutches of eggs in shallow nests dug into the ground, with the number of eggs varying between 2 to 6 eggs per clutch.',
        warn: 'Conservation efforts are crucial for protecting these tortoises, as they face threats from habitat destruction, collection for the pet trade, and other human-induced pressures.',
        preserve: 'As an emblem of resilience and natural beauty, the Elongated Tortoise highlights the importance of conservation efforts aimed at preserving their habitats and fostering a harmonious balance between humans and wildlife.',
        pic1: '/ETortoise2.jpg',
        pic2: '/ETortoise3.jpg',
    },
    {
        id: 21,
        url: '/amboinaBoxTurtle.jpg',
        title: 'Amboina Box Turtle',
        body: 'The Amboina box turtle, originating from Indonesia, is recognized for its vibrant shell and unique pattern. This small-sized turtle is sought after in the exotic pet trade due to its striking appearance and rarity.',
        intro: 'Amboina Box Turtle, a mesmerizing reptile known for its unique appearance and endearing characteristics. A creature adorned with a captivating shell and a distinct charm that captivates enthusiasts worldwide.',
        appear: 'One of its most captivating features is its beautifully patterned carapace, often showcasing a mix of intricate markings and colors, varying from dark brown to vibrant shades of red, orange, and yellow.',
        HWM: 'They typically measure about 15 to 18 centimeters (6 to 7 inches) in carapace length and can weigh approximately 500 to 700 grams (1.1 to 1.5 pounds) on average.',
        HWF: ' Females are generally a bit smaller, measuring around 12 to 15 centimeters (5 to 6 inches) in carapace length and weighing approximately 400 to 600 grams (0.9 to 1.3 pounds) on average.',
        lifeStyle: 'The Amboina Box Turtle, scientifically named Cuora amboinensis, is a striking species native to Southeast Asia, specifically found in regions such as Indonesia, Malaysia, and the Philippines. These turtles exhibit a distinctive shell shape that allows them to retract their limbs and head fully within their shell, providing exceptional protection from predators—a trait from which they derive their name "box turtle."',
        food: 'Amboina Box Turtles are primarily terrestrial, inhabiting both forests and grasslands near freshwater sources. They are omnivorous, feeding on a diet consisting of various plants, fruits, insects, and occasionally small vertebrates.',
        fun1: 'Females lay small clutches of eggs in nests dug into the ground, with incubation lasting several months before hatching.',
        fun2: 'Amboina Box Turtles are known for their calm and gentle nature, making them appealing as pets among reptile enthusiasts.',
        fun3: 'They derive their name from their unique ability to retract their limbs and head fully within their shell, providing them with exceptional protection.',
        warn: 'Conservation efforts are crucial for safeguarding these turtles, classified as vulnerable, due to the aforementioned threats and their restricted habitat range.',
        preserve: 'The Amboina Box Turtle serves as a symbol of beauty and vulnerability, emphasizing the importance of preserving their natural habitats and raising awareness to ensure their continued existence in the wild.',
        pic1: '/BTurtle2.jpg',
        pic2: '/BTurtle3.jpg',
    },
    {
        id: 22,
        url: '/threeStripedBoxTurtle.jpg',
        title: 'Three-striped Box Turtle',
        body: 'The Three-Striped Box Turtle, native to Southeast Asia, features three distinctive yellow stripes on its dark shell. Popular in the pet trade, this species is valued for its unique appearance and manageable size.',
        intro: 'Step into the captivating world of the Three-Striped Box Turtle, a fascinating reptile revered for its unique traits and captivating behaviors. Envision a creature boasting a stunning shell adorned with vivid patterns, showcasing a blend of grace and durability.',
        appear: 'With its defining feature being three prominent stripes adorning its carapace, ranging in colors from black and brown to vibrant shades of red, this turtle exhibits a visual spectacle amidst intricate patterns on its shell.',
        HWM: 'They generally measure about 13 to 15 centimeters (5 to 6 inches) in carapace length and can weigh approximately 300 to 400 grams (0.7 to 0.9 pounds) on average.',
        HWF: 'Females are usually a bit smaller, measuring around 12 to 14 centimeters (4.7 to 5.5 inches) in carapace length and weighing approximately 250 to 350 grams (0.6 to 0.8 pounds) on average.',
        lifeStyle: 'The Three-Striped Box Turtle, scientifically named Cuora trifasciata, is an intriguing species native to various Southeast Asian regions, including parts of China, Vietnam, and Laos. Distinguished by a protective shell allowing it to retract completely, this species embodies the characteristics of box turtles, providing them with a formidable defense mechanism against potential threats.',
        food: 'Primarily terrestrial, these turtles inhabit forested areas near freshwater sources, where they sustain themselves on an omnivorous diet consisting of plants, fruits, insects, and sporadic small vertebrates.',
        fun1: 'he shell of the Three-Striped Box Turtle allows it to retract its head and limbs fully, providing a secure refuge from predators, giving rise to their classification as box turtles.',
        fun2: 'In certain cultures, Three-Striped Box Turtles are revered for their symbolism, representing longevity and wisdom in local folklore and traditions.',
        fun3: 'Females lay small clutches of eggs in nests dug into the ground, with an incubation period lasting several months before hatching.',
        warn: 'Despite their allure, these turtles confront significant challenges, facing threats due to habitat destruction, illegal pet trade activities, and human intervention.',
        preserve: 'Preservation efforts are imperative to protect the vulnerable status of this species and conserve their natural habitats, ensuring their survival and fostering a harmonious coexistence with humans in their native environments.',
        pic1: '/TBTurtle2.jpg',
        pic2: '/TBTurtle3.jpg',
    },
    {
        id: 23,
        url: '/spinyFrog.jpg',
        title: 'Spiny Frog',
        body: 'The Spiny Frog, is a species of frog found in East and Southeast Asia. It is identifiable by its spiny appearance, with rough, spiky skin, and is known for its adaptation to both terrestrial and aquatic habitats.',
        intro: 'Spiny Frog, a unique amphibian renowned for its distinct appearance and fascinating adaptations.',
        appear: 'One of its most striking features is its body covered with pointed spines or tubercles, adding to its distinctive appearance. These spines act as a defense mechanism against predators, deterring potential threats.',
        HWM: 'They typically measure about 5 to 7 centimeters (2 to 2.8 inches) in body length.',
        HWF: 'Females are generally a bit larger, measuring around 6 to 8 centimeters (2.4 to 3.1 inches) in body length.',
        lifeStyle: 'Spiny Frogs are semi-aquatic creatures, often found in and around freshwater habitats such as streams, ponds, and forested areas. They spend their time both in water and on land, displaying adaptability in their habitat preferences. They have a unique breeding behavior, with males known for their distinct advertisement calls during the mating season, often heard as a chorus in breeding areas.',
        food: 'Their diet primarily consists of insects, small invertebrates, and occasionally, plant matter, showcasing their omnivorous feeding habits.',
        fun1: 'During mating seasons, males produce distinctive advertisement calls to attract females, often leading to chorus-like sounds in breeding areas.',
        fun2: 'The spines or tubercles covering their bodies serve as a deterrent to predators, making them less palatable or more challenging to consume.',
        fun3: 'Individual frogs can exhibit slight variations in coloration and the arrangement of spines, adding to their diversity.',
        warn: 'Conservation efforts are vital to preserve these fascinating amphibians, ensuring the protection of their natural habitats and maintaining the delicate balance of their ecosystems.',
        preserve: 'The Spiny Frog symbolizes resilience and uniqueness, emphasizing the significance of conservation measures to safeguard their populations and appreciate their contributions to the biodiversity of their habitats.',
        pic1: '/spinyF2.png',
        pic2: '/spinyF3.jpg',
    },
    {
        id: 24,
        url: '/Ceacilian.jpg',
        title: 'Glutinous Caecilian',
        body: 'The Glutinous Caecilian, found in parts of Southeast Asia, are recognizable by their smooth, glossy appearance and their predominantly subterranean lifestyle.',
        intro: 'Imagine a creature resembling an elongated worm, living a secretive life beneath the soils surface, embodying both mystery and resilience. That is the Glutinous Caecilian',
        appear: 'One of its distinctive traits is its cylindrical body covered in a slippery, mucus-like coating, enabling it to glide smoothly through the underground burrows it inhabits.',
        HWM: 'On average, Glutinous Caecilians typically range in size between 20 to 30 centimeters (8 to 12 inches) in length',
        HWF: 'Caecilians, in general, often exhibit minimal sexual dimorphism in size or external characteristics. The exact size difference between males and females may not be significantly pronounced.',
        lifeStyle: 'Glutinous Caecilians are fossorial creatures, spending most of their lives burrowed underground in moist soil or leaf litter, rarely coming to the surface. This burrowing lifestyle aids in both protection from predators and access to a suitable environment for their diet and reproduction.',
        food: 'As carnivorous amphibians, they feed on small invertebrates such as earthworms, termites, and insect larvae, using specialized sensory organs to detect prey in their subterranean habitat.',
        fun1: 'Caecilians lack limbs, resembling elongated worms or snakes, but they are not reptiles; they belong to the amphibian group.',
        fun2: 'They possess specialized sensory organs called tentacles, which help in detecting prey and navigating their subterranean habitat.',
        fun3: 'These amphibians create tunnels using their pointed heads, moving through the soil to seek shelter and locate food.',
        warn: 'Despite their elusive nature and limited interactions with humans, Glutinous Caecilians face threats from habitat loss due to human activities and changing environmental conditions.',
        preserve: 'Conservation efforts are essential to protect these amphibians and their subterranean habitats, highlighting the importance of understanding and preserving the delicate balance of underground ecosystems.',
        pic1: '/ceacilian2.jpg',
        pic2: '/ceacilian3.jpg',
    },
    {
        id: 25,
        url: '/firebellyToad.jpg',
        title: 'Yunnan Firebelly Toad',
        body: 'The Yunnan Firebelly Toad, boasts a striking red or orange underside and prefers forested areas near water. Popular in the pet trade due to its eye-catching appearance and small size.',
        intro: 'Step into the intriguing world of the Yunnan Firebelly Toad, a captivating amphibian revered for its striking appearance and unique coloration. Picture a diminutive frog adorned with radiant tones, showcasing both allure and individuality.',
        appear: 'One of its most striking features is its colorful appearance, with bright hues of red, orange, or yellow on its underside, resembling a striking "fire belly." This serves as a warning signal to predators, indicating its toxic nature.',
        HWM: 'On average, these toads measure between 4 to 5 centimeters (around 1.5 to 2 inches) in length.',
        HWF: 'Typically, males and females exhibit similar sizes.',
        lifeStyle: 'These toads predominantly inhabit freshwater locales like ponds, marshes, and slow-moving streams within forested landscapes, illustrating their adaptability to diverse environments.',
        food: 'They possess semi-aquatic lifestyles, spending time both in water and on land. Their diet consists primarily of small invertebrates, insects, and occasionally small aquatic creatures.',
        fun1: 'Yunnan Firebelly Toads secrete toxins from their skin, making them unpalatable or potentially harmful to predators.',
        fun2: 'The bright coloration on their undersides acts as a visual warning to predators, alerting them to the toad toxicity.',
        fun3: 'Yunnan Firebelly Toads undergo breeding migrations to suitable water bodies, where they lay their eggs in water or marshy areas.',
        warn: 'Conservation efforts are essential to protect these toads due to habitat degradation and pollution affecting their natural environments.',
        preserve: 'The Yunnan Firebelly Toad symbolizes vibrancy and natural defense mechanisms, highlighting the significance of preserving their habitats and maintaining ecological balance in their native ecosystems.',
        pic1: '/FToad2.png',
        pic2: '/FToad3.jpg',
    },
    {
        id: 26,
        url: '/toad.jpg',
        title: 'Burmese Horned Toad',
        body: 'The Burmese Horned Toad is a Southeast Asian frog known for its rough skin and horn-like projections above its eyes. Often found in Myanmar forests, it tends to be secretive in nature.',
        intro: 'Burmese Horned Toad, an extraordinary amphibian celebrated for its unique appearance and distinctive features. Envision a captivating toad adorned with remarkable horn-like projections, embodying both charm and resilience.',
        appear: 'One of its most striking characteristics is its appearance, with prominent horn-like projections on its head, giving it a distinct and captivating look that aids in camouflage within its environment.',
        HWM: 'On average, Burmese Horned Toads measure between 5 to 8 centimeters (around 2 to 3 inches) in length',
        HWF: 'Typically, there is not a considerable size difference between males and females in this species.',
        lifeStyle: 'These toads inhabit various habitats, including forests, grasslands, and sometimes even disturbed areas, showcasing their adaptability to diverse ecosystems. Burmese Horned Toads are primarily terrestrial and nocturnal, spending their days hidden under leaf litter or soil, emerging at night to forage for prey.',
        food: 'Their diet mainly consists of insects, small invertebrates, and occasionally smaller frogs or reptiles, showcasing their predatory habits.',
        fun1: 'When threatened, they rely on their camouflage and stay motionless, utilizing their cryptic coloration to evade detection.',
        fun2: 'Burmese Horned Toads are primarily terrestrial, preferring to dwell on the ground rather than in water like many other amphibians.',
        fun3: 'Females lay eggs in moist areas, such as leaf litter or damp soil, and the tadpoles develop in these locations after hatching.',
        warn: 'Conservation efforts are crucial to protect these toads from habitat loss due to human activities and other environmental threats, ensuring the preservation of their natural habitats.',
        preserve: 'The Burmese Horned Toad represents uniqueness and adaptation, underscoring the importance of understanding and conserving these captivating amphibians within their native ecosystems.',
        pic1: '/HToad2.jpg',
        pic2: '/HToad3.jpg',
    },
    {
        id: 27,
        url: '/kingCobra.jpg',
        title: 'King Cobra',
        body: 'The King Cobra, the world longest venomous snake, is found in South and Southeast Asia. Knowned for its impressive size, distinctive hood, and potent venom.',
        intro: 'Welcome to the mesmerizing realm of the King Cobra, a majestic serpent revered for its impressive size, distinctive appearance, and fascinating behaviors. Imagine an iconic snake adorned with a hood, embodying both power and grace.',
        appear: 'One of its most striking features is its hood, which it can expand when threatened, displaying intimidating markings and creating a silhouette reminiscent of a cobra "hood."',
        HWM: 'King Cobras are known to reach lengths between 3.7 to 4 meters (12 to 13 feet) for males, regarding weight, males might weigh around 6 to 9 kilograms (13 to 20 pounds)',
        HWF: ' While females can weigh approximately 5 to 7 kilograms (11 to 15 pounds) and reach to the lenght of 3 to 3.4 meters (10 to 11 feet).',
        lifeStyle: 'These serpents inhabit diverse habitats, including dense forests, grasslands, and occasionally human-populated areas, showcasing their adaptability to varying environments. Renowned for their potent venom, they possess neurotoxic venom that can subdue and kill their prey swiftly, making them apex predators in their ecosystems.',
        food: 'King Cobras are predominantly diurnal, actively hunting during the day, and primarily feed on other snakes, including venomous species, as well as small mammals and birds.',
        fun1: 'King Cobra venom is highly neurotoxic and can cause respiratory failure in their prey, delivering enough venom in one bite to kill an elephant.',
        fun2: 'Known for their intelligence and agility, King Cobras possess a keen sense of sight and smell, aiding in hunting and navigation.',
        fun3: 'They primarily feed on other snakes, including venomous ones, as well as lizards, small mammals, and birds, making them apex predators in their ecosystems.',
        warn: 'Conservation efforts are vital to protect these snakes, as they face habitat loss, human encroachment, and persecution due to their venomous nature.',
        preserve: 'The King Cobra symbolizes both fear and respect, underscoring the importance of conserving these magnificent creatures and fostering a harmonious coexistence within their natural habitats.',
        pic1: '/kingCobra2.jpg',
        pic2: '/kingCobra3.jpg',
    },
    {
        id: 28,
        url: '/bandedKrait.jpg',
        title: 'Banded Krait',
        body: 'The Banded Krait is a venomous snake with a distinctive black-and-white banded pattern, found in Southeast Asia, known for its potent venom.',
        intro: 'Banded Krait, a fascinating and venomous snake celebrated for its striking appearance and unique traits. ',
        appear: 'The Banded Krait, scientifically known as Bungarus fasciatus, is a venomous species native to various regions across Southeast Asia, commonly found in countries like Thailand, Malaysia, Indonesia, and parts of India. One of its most remarkable features is its distinctive coloration, displaying alternating bands of black and white or yellow, contributing to its striking appearance and serving as a warning to potential predators.',
        HWM: 'On average, Banded Kraits can reach lengths between 1 to 1.5 meters (3 to 5 feet).',
        HWF: 'Typically, both sexes have a similar body size and appearance.',
        lifeStyle: 'These serpents primarily inhabit diverse habitats, including forests, grasslands, and sometimes human-altered environments, showcasing their adaptability to various landscapes',
        food: 'Banded Kraits are predominantly nocturnal, actively hunting at night, and their diet mainly consists of other snakes, reptiles, and occasionally small mammals.',
        fun1: 'Despite their venomous nature, they are generally shy and try to avoid confrontation with humans or potential threats.',
        fun2: 'They possess potent neurotoxic venom, making them one of the deadliest snakes in their range.',
        fun3: 'They prefer residing in burrows, holes, or dense vegetation during the day, displaying secretive behavior.',
        warn: 'Conservation efforts are crucial to protect these snakes, as they face habitat loss, human encroachment, and persecution due to their venomous nature.',
        preserve: 'The Banded Krait symbolizes both allure and peril, emphasizing the importance of understanding and conserving these captivating serpents within their native habitats.',
        pic1: '/Krait2.jpg',
        pic2: '/Krait3.jpg',
    },
    {
        id: 29,
        url: '/macaque.jpg',
        title: 'Pig-tailed Macaque',
        body: 'The Southern Pig-tailed Macaque, found in Southeast Asia, is identified by its pig-like tail. Known for adaptability and intelligence, it resides in diverse habitats.',
        intro: 'Pig-tailed Macaque, an intelligent and social primate known for its distinctive appearance and intriguing behaviors.',
        appear: 'Pig-tailed Macaque most distinctive features is its short tail, which is reminiscent of a pig tail, giving rise to its common name and distinguishing it from other macaque species.',
        HWM: 'On average, male Pig-tailed Macaques can weigh between 5 to 10 kilograms (11 to 22 pounds) and measure around 50 to 65 centimeters (20 to 26 inches) in body length. ',
        HWF: 'Meanwhile, females usually weigh between 3 to 7 kilograms (6.6 to 15.4 pounds) and measure around 40 to 55 centimeters (16 to 22 inches) in body length.',
        lifeStyle: 'Pig-tailed Macaques are highly social creatures, living in troops that can consist of several individuals, and they engage in complex social interactions, including grooming, playing, and establishing hierarchical structures.',
        food: 'They showcase a diverse diet, consuming fruits, leaves, seeds, insects, and occasionally small vertebrates, displaying their adaptability to varied food sources.',
        fun1: 'These macaques exhibit high intelligence, using tools, displaying problem-solving skills, and having a wide range of vocalizations for communication.',
        fun2: 'They communicate through various vocalizations, facial expressions, and body language, conveying different messages within their troop.',
        fun3: 'Females exhibit strong maternal instincts, caring for and nurturing their offspring within the troop.',
        warn: 'Conservation efforts are vital to protect these macaques as they face threats from habitat destruction, hunting, and capture for the illegal pet trade.',
        preserve: 'The Pig-tailed Macaque symbolizes both resilience and sociability, underscoring the importance of understanding and conserving these delightful primates within their native habitats.',
        pic1: '/PTMacaque2.jpg',
        pic2: '/PTMacaque3.jpg',
    },
    {
        id: 30,
        url: '/macaque2.jpg',
        title: 'Stump-tailed Macaque',
        body: 'The Stump-tailed Macaque, found in Southeast Asia, is known for its short tail. This primate species inhabits various forested areas and demonstrates social behavior within its groups.',
        intro: 'Stump-tailed Macaque, an intelligent and adaptable primate celebrated for its distinctive appearance and intriguing behaviors. Imagine an expressive monkey with a short tail and a robust build, embodying both resilience and sociability.',
        appear: 'The Stump-tailed Macaque, scientifically known as Macaca arctoides, is a species of Old World monkey found in various regions of Southeast Asia. One of its most distinctive features is its short tail, which appears truncated, resembling a stump, thus giving rise to its common name.',
        HWM: 'On average, male Stump-tailed Macaques can weigh between 8 to 13 kilograms (17 to 29 pounds) and measure around 55 to 65 centimeters (22 to 26 inches) in body length. ',
        HWF: 'Meanwhile, females usually weigh between 5 to 9 kilograms (11 to 20 pounds) and measure around 45 to 55 centimeters (18 to 22 inches) in body length.',
        lifeStyle: 'These macaques typically inhabit diverse habitats, including tropical forests, mountainous regions, and sometimes even near human settlements, showcasing their adaptability to varying environments. Stump-tailed Macaques are highly social creatures, living in troops that can consist of several individuals. They engage in complex social interactions, grooming, and hierarchical structures within their groups.',
        food: 'Their diet is varied, including fruits, leaves, seeds, insects, and occasionally small vertebrates, showcasing their ability to adapt to a range of food sources.',
        fun1: 'Some populations have shown tool usage behavior, using objects like sticks or stones for various purposes.',
        fun2: 'They demonstrate problem-solving skills and exhibit curiosity, adapting to new situations and challenges within their environment.',
        fun3: 'Females exhibit strong maternal instincts, caring for and nurturing their offspring within the troops social structure.',
        warn: 'Conservation efforts are vital to protect these macaques as they face threats from habitat destruction, hunting, and capture for the illegal pet trade.',
        preserve: 'The Stump-tailed Macaque symbolizes adaptability and social bonds, underscoring the importance of understanding and conserving these charming primates within their native habitats.',
        pic1: '/STMacaque2.jpg',
        pic2: '/STMacaque3.jpg',
    },
    {
        id: 31,
        url: '/catBaLungurs.jpg',
        title: 'Cat Ba Lungurs',
        body: 'Cat Ba Langurs, from Cat Ba Island in Vietnam, are recognized by their white heads and long tails.',
        intro: 'Welcome to the fascinating realm of the Cat Ba Langurs, an enigmatic and critically endangered primate species celebrated for its uniqueness and conservation significance.',
        appear: 'The Cat Ba Langur, scientifically known as Trachypithecus poliocephalus, is a rare and endangered leaf-eating monkey found exclusively on Cat Ba Island in Vietnam Halong Bay.The Lungurs with a predominantly black body adorned with striking white fur around its face and golden-brown fur on its head and limbs, giving it a distinct and alluring appearance.',
        HWM: 'On average, Cat Ba Langurs tend to have a body length ranging from approximately 50 to 60 centimeters (20 to 24 inches) and a weight that can vary between 5 to 7 kilograms (11 to 15 pounds).',
        HWF: ' The males possibly being slightly larger and heavier than females.',
        lifeStyle: 'These langurs primarily inhabit limestone forests and karst landscapes, displaying remarkable adaptations to this specific environment on Cat Ba Island. Cat Ba Langurs live in small social groups, known as troops, and exhibit complex social interactions, including grooming, playing, and establishing social hierarchies.',
        food: 'Their diet mainly comprises leaves, fruits, and flowers, showcasing their specialized feeding habits within their limited habitat.',
        fun1: 'Cat Ba Langurs are exclusively found on Cat Ba Island in Vietnam Halong Bay, making them highly localized and critically endangered due to their limited distribution.',
        fun2: 'Females exhibit strong maternal instincts, caring for and protecting their offspring within the troop social structure.',
        fun3: 'They use a range of vocalizations and gestures to communicate within their troop, conveying various messages and social cues',
        warn: 'Regrettably, Cat Ba Langurs face severe threats from habitat loss due to deforestation, illegal hunting, and limited distribution, pushing them towards the brink of extinction.',
        preserve: 'Conservation efforts are paramount to protect these critically endangered langurs, including habitat preservation, anti-poaching measures, and community engagement for their conservation.',
        pic1: '/Lungurs2.jpg',
        pic2: '/Lungurs3.jpg',
    },
    {
        id: 32,
        url: '/greyLangurs.jpg',
        title: 'Indochinese Grey Langur',
        body: 'The Indochinese Grey Langur, native to Southeast Asia, is a primate species known for its gray fur. These langurs live in forested areas and exhibit social behavior within their groups.',
        intro: 'Grey Langur, an intriguing and expressive primate species celebrated for its unique appearance and social behavior. Picture a graceful and agile monkey with varying shades of grey fur, displaying both elegance and intelligence.',
        appear: 'One of its notable characteristics is its varying shades of grey fur, ranging from silver-grey to dark grey, sometimes with hints of brown or black, giving them a distinctive and appealing appearance.',
        HWM: 'On average, male Indochinese Grey Langurs can have a body length ranging from about 45 to 65 centimeters (18 to 26 inches) and weigh between 5 to 8 kilograms (11 to 18 pounds).',
        HWF: 'Meanwhile, females generally have a body length ranging from 40 to 60 centimeters (16 to 24 inches) and weigh between 4 to 7 kilograms (9 to 15 pounds).',
        lifeStyle: 'Indochinese Grey Langurs live in troops, displaying complex social interactions, including grooming, playing, and establishing social hierarchies within their groups.',
        food: 'Their diet mainly consists of leaves, fruits, seeds, and occasionally insects, exhibiting specialized feeding habits adapted to their ecological niche.',
        fun1: 'Indochinese Grey Langurs are adept climbers, using their agility to move through the trees and navigate their habitat efficiently.',
        fun2: 'Some populations have exhibited tool usage behavior, using sticks or objects for various purposes.',
        fun3: 'They use a variety of vocalizations and gestures to communicate within their troop, conveying various messages and social cues.',
        warn: '',
        preserve: 'Conservation efforts are vital for their survival as they face threats from habitat loss due to deforestation, hunting, and human encroachment, emphasizing the need for protective measures.',
        pic1: '/Langur2.jpg',
        pic2: '/Langur3.jpg',
    },
    {
        id: 33,
        url: '/larGibbon.jpg',
        title: 'Lar Gibbon',
        body: 'The Lar Gibbon, a primate in Southeast Asia, is known for its small size, long arms for swinging, and complex vocalizations. They form monogamous pairs and live in forested areas.',
        intro: 'Lar Gibbon, an agile and melodious ape celebrated for its aerial acrobatics and soulful calls.',
        appear: 'These gibbons showcase distinctive fur coloration, varying between different subspecies, displaying hues of light to dark brown, black, or even blond, with the characteristic lighter fur encircling their faces.',
        HWM: 'On average, male Lar Gibbons have a body length ranging from approximately 44 to 64 centimeters (17 to 25 inches) and weigh between 5 to 8 kilograms (11 to 18 pounds). ',
        HWF: 'Females generally exhibit a body length ranging from 40 to 57 centimeters (16 to 22 inches) and weigh between 4 to 6 kilograms (9 to 13 pounds).',
        lifeStyle: 'Lar Gibbons exhibit an arboreal lifestyle, spending most of their time in the forest canopy, where they move with astonishing agility and grace by swinging from branch to branch—a behavior known as brachiation.',
        food: 'Lar Gibbons have a frugivorous diet, primarily consisting of fruits, supplemented with leaves, flowers, and occasionally insects, showcasing their dietary adaptability.',
        fun1: 'They form monogamous bonds, living in pairs with their offspring, displaying strong family cohesion within their territories.',
        fun2: 'Compared to other apes, they have relatively small body sizes, with slender limbs and a slender build suited for an arboreal lifestyle.',
        fun3: 'They are skilled brachiators, swinging through the trees using their long arms, displaying remarkable agility and speed while traversing the forest canopy.',
        warn: 'Threats such as habitat loss due to deforestation, hunting, and illegal pet trade pose significant dangers to their populations, warranting conservation measures for their protection.',
        preserve: 'The Lar Gibbon symbolizes both grace and a captivating serenade, highlighting the importance of understanding and preserving these enchanting apes and their habitats.',
        pic1: '/Gibbon2.jpg',
        pic2: '/Gibbon3.jpg',
    },
    {
        id: 34,
        url: '/alpaca5.jpg',
        title: 'Alapca',
        body: 'Alpacas, South American camelids, are prized for their soft fleece used in textiles. Known for their gentle nature, they are also kept as pets or for therapy.',
        intro: 'Picture a graceful and fluffy camelid roaming the Andean highlands, embodying both elegance and utility.Alpaca, a domesticated species celebrated for its gentle nature and luxurious fleece.',
        appear: 'These endearing creatures are known for their soft and insulating fleece, which comes in various natural colors, including white, black, brown, and grey, and is highly prized for its warmth and hypoallergenic properties.',
        HWM: 'Alpacas stand approximately 81 to 99 centimeters (32 to 39 inches) tall at the shoulder , with males typically weighing between 64 to 79 kilograms (140 to 175 pounds) ',
        HWF: 'Females with the same height as the male and weighing around 55 to 65 kilograms (121 to 143 pounds).',
        lifeStyle: 'Alpacas are social herd animals that live in family groups, displaying a strong sense of community within their herds. They communicate through soft hums, ear and tail movements, and body language.',
        food: 'Their diet mainly consists of grasses and hay, and they are efficient grazers, capable of thriving in harsh environments with limited vegetation.',
        fun1: 'Unlike other farm animals, Alpacas have a gentle impact on pastures, as they graze without pulling the roots from the ground.',
        fun2: 'Alpacas have a three-chambered stomach, similar to other camelids, which aids in efficient digestion of fibrous plant material.',
        fun3: 'Alpacas have been domesticated for over 6,000 years by Andean cultures in South America, primarily for their fleece.',
        warn: '',
        preserve: 'The Alpaca symbolizes both practicality and charm, highlighting the significance of these animals within the cultural, economic, and ecological landscapes of the Andean regions.',
        pic1: '/alpacaVer2.jpg',
        pic2: '/alpacaVer3.jpg',
    }
]

AnimalData.forEach((animal, index) => {
    animal.id = index + 1; // Gán giá trị id mới bằng chỉ số tương ứng + 1
});

export default AnimalData